/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuthorizedResponse
 */
export interface AuthorizedResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthorizedResponse
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthorizedResponse
     */
    isAuthorized: boolean;
}

/**
 * Check if a given object implements the AuthorizedResponse interface.
 */
export function instanceOfAuthorizedResponse(value: object): value is AuthorizedResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('isAuthorized' in value) || value['isAuthorized'] === undefined) return false;
    return true;
}

export function AuthorizedResponseFromJSON(json: any): AuthorizedResponse {
    return AuthorizedResponseFromJSONTyped(json, false);
}

export function AuthorizedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'isAuthorized': json['isAuthorized'],
    };
}

  export function AuthorizedResponseToJSON(json: any): AuthorizedResponse {
      return AuthorizedResponseToJSONTyped(json, false);
  }

  export function AuthorizedResponseToJSONTyped(value?: AuthorizedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'isAuthorized': value['isAuthorized'],
    };
}

