  - name: Secret for tldraw valkey
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
    when: ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
    tags:
      - 1password

  - name: Install valkey sentinel
    kubernetes.core.helm:
      chart_ref: oci://docker.io/bitnamicharts/valkey
      chart_version: "{{ TLDRAW_VALKEY_CHART_VERSION }}"
      release_name: valkey
      release_namespace: "{{ NAMESPACE }}"
      release_state: present
      create_namespace: yes
      kubeconfig: ~/.kube/config
      update_repo_cache: no
      values:
        global:
          defaultStorageClass: "{{ SC_DEFAULT_STORAGE_CLASS_NAME }}"
        auth:
          existingSecret: tldraw-valkey-password
          existingSecretPasswordKey: REDIS_SENTINEL_PASSWORD
        master:
          readinessProbe:
            timeoutSeconds: 5
        sentinel:
          enabled: true
          readinessProbe:
            timeoutSeconds: 5
        metrics:
          enabled: true
          podMonitor:
            enabled: true
          serviceMonitor:
            enabled: true
        # OPS-6762 still up to debate if we will enable this
        networkPolicy:
          enabled: false
        serviceAccount:
          create: false
        # https://github.com/bitnami/charts/issues/9689
        useHostnames: false
        resources:
          limits:
            cpu: "{{ TLDRAW_VALKEY_CPU_LIMITS|default('1000m', true) }}"
            memory: "{{ TLDRAW_VALKEY_MEMORY_LIMITS|default('4Gi', true) }}"
          requests:
            cpu: "{{ TLDRAW_VALKEY_CPU_REQUESTS|default('100m', true) }}"
            memory: "{{ TLDRAW_VALKEY_MEMORY_REQUESTS|default('1Gi', true) }}"
    tags:
      - helm
