galaxy_info:
  role_name: tldraw-server
  author: Schul-Cloud Verbund
  description: tldraw-server
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
